import { describe, it, expect, vi } from 'vitest';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import {
  resolveCredential,
  assertPrivateKeyArgAllowed,
  isLocalEnvironment,
  CredentialError,
} from '../src/lib/credentials.js';
import { decryptKeystore, loadKeystoreFile, KEYSTORE_DECRYPT_FAILED } from '../src/lib/keystore.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Anvil account 3 — a published, deliberately-public Foundry development key. Safe to embed.
const ANVIL_KEY = '0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6';

// Test keystores for a throwaway key. Both encrypt the SAME private key under the SAME
// passphrase, so the two KDF paths are checked against one expected value.
//
//   keystore-pbkdf2.json — the canonical Web3 Secret Storage V3 pbkdf2 test vector, published
//     in the spec itself. Decrypting it proves spec conformance, not just self-consistency.
//   keystore-scrypt.json — generated by ethers v6 (independent reference implementation).
//     The spec's scrypt vector uses n=262144,r=1, which OpenSSL refuses (it enforces
//     n < 2^(128r/8), i.e. n < 65536 when r=1), so it cannot be used from Node. Real geth /
//     ethers keystores use r=8, which is what this fixture exercises. It also happens to use
//     the capitalised "Crypto" key, covering that spelling.
const VECTOR_PASSPHRASE = 'testpassword';
const VECTOR_PRIVATE_KEY = '0x7a28b5ba57c53603b0b07b56bba752f7784bf506fa95edc395f5cf6c7514fe9d';
const PBKDF2_KEYSTORE = join(__dirname, 'fixtures', 'keystore-pbkdf2.json');
const SCRYPT_KEYSTORE = join(__dirname, 'fixtures', 'keystore-scrypt.json');

const noopWarn = () => {};

describe('V7 — operator key must not travel on argv', () => {
  describe('assertPrivateKeyArgAllowed', () => {
    it('permits --private-key for local (Anvil keys are public by design)', () => {
      expect(() => assertPrivateKeyArgAllowed('local')).not.toThrow();
    });

    it.each(['testnet', 'mainnet'])('refuses --private-key for %s', (env) => {
      expect(() => assertPrivateKeyArgAllowed(env)).toThrow(CredentialError);
      expect(() => assertPrivateKeyArgAllowed(env)).toThrow(/not permitted/i);
    });

    // Fail closed: an unrecognised environment string must never be treated as local.
    it('refuses --private-key for an unrecognised environment', () => {
      expect(() => assertPrivateKeyArgAllowed('LOCAL')).toThrow(CredentialError);
      expect(() => assertPrivateKeyArgAllowed('')).toThrow(CredentialError);
    });

    it('isLocalEnvironment only matches exactly "local"', () => {
      expect(isLocalEnvironment('local')).toBe(true);
      expect(isLocalEnvironment('localhost')).toBe(false);
      expect(isLocalEnvironment('Local')).toBe(false);
    });
  });

  describe('resolveCredential', () => {
    it('accepts -k for local and returns the key', async () => {
      const result = await resolveCredential({
        env: 'local',
        privateKeyArg: ANVIL_KEY,
        warn: noopWarn,
      });
      expect(result.source).toBe('argv');
      expect(result.privateKey).toBe(ANVIL_KEY);
    });

    it.each(['testnet', 'mainnet'] as const)('rejects -k for %s', async (env) => {
      await expect(
        resolveCredential({ env, privateKeyArg: ANVIL_KEY, warn: noopWarn })
      ).rejects.toThrow(/not permitted/i);
    });

    // The flag is rejected even when it would have been unused, so operators never build the
    // habit on a --dry-run and then leak a real key by dropping the flag.
    it('rejects -k on non-local even alongside --build-only or --dry-run', async () => {
      await expect(
        resolveCredential({
          env: 'mainnet',
          privateKeyArg: ANVIL_KEY,
          buildOnly: true,
          warn: noopWarn,
        })
      ).rejects.toThrow(/not permitted/i);
      await expect(
        resolveCredential({
          env: 'mainnet',
          privateKeyArg: ANVIL_KEY,
          dryRun: true,
          warn: noopWarn,
        })
      ).rejects.toThrow(/not permitted/i);
    });

    it('rejection message points at --keystore and --build-only', async () => {
      await expect(
        resolveCredential({ env: 'mainnet', privateKeyArg: ANVIL_KEY, warn: noopWarn })
      ).rejects.toThrow(/--build-only[\s\S]*--keystore|--keystore[\s\S]*--build-only/);
    });

    it('rejects a malformed key from argv without echoing it', async () => {
      const secret = '0xdeadbeef';
      const error = await resolveCredential({
        env: 'local',
        privateKeyArg: secret,
        warn: noopWarn,
      }).catch((e: Error) => e);
      expect(error).toBeInstanceOf(CredentialError);
      expect((error as Error).message).not.toContain(secret);
    });

    it('needs no credential for --build-only', async () => {
      const result = await resolveCredential({ env: 'mainnet', buildOnly: true, warn: noopWarn });
      expect(result.source).toBe('none');
      expect(result.privateKey).toBeUndefined();
    });

    it('errors with actionable guidance when nothing is supplied', async () => {
      await expect(resolveCredential({ env: 'mainnet', warn: noopWarn })).rejects.toThrow(
        /--build-only/
      );
    });

    // --private-key must not appear in the mainnet guidance; suggesting it would recreate V7.
    it('does not advertise --private-key in non-local guidance', async () => {
      const error = await resolveCredential({ env: 'mainnet', warn: noopWarn }).catch(
        (e: Error) => e
      );
      expect((error as Error).message).not.toMatch(/--private-key <key>/);
    });

    it('accepts OPERATOR_PRIVATE_KEY on local without warning', async () => {
      const warn = vi.fn();
      const result = await resolveCredential({ env: 'local', envPrivateKey: ANVIL_KEY, warn });
      expect(result.source).toBe('env');
      expect(warn).not.toHaveBeenCalled();
    });

    it('accepts OPERATOR_PRIVATE_KEY on mainnet but warns', async () => {
      const warn = vi.fn();
      const result = await resolveCredential({ env: 'mainnet', envPrivateKey: ANVIL_KEY, warn });
      expect(result.source).toBe('env');
      expect(warn).toHaveBeenCalledOnce();
      // The warning must not contain the key itself.
      expect(warn.mock.calls[0][0]).not.toContain(ANVIL_KEY);
    });
  });

  describe('keystore path', () => {
    it('resolves a keystore on mainnet via the passphrase prompt', async () => {
      const promptPassphrase = vi.fn().mockResolvedValue(VECTOR_PASSPHRASE);
      const result = await resolveCredential({
        env: 'mainnet',
        keystorePath: PBKDF2_KEYSTORE,
        promptPassphrase,
        warn: noopWarn,
      });
      expect(promptPassphrase).toHaveBeenCalledOnce();
      expect(result.source).toBe('keystore');
      expect(result.privateKey).toBe(VECTOR_PRIVATE_KEY);
    });

    it('uses SWR_KEYSTORE_PASSWORD instead of prompting when set', async () => {
      const promptPassphrase = vi.fn();
      const result = await resolveCredential({
        env: 'mainnet',
        keystorePath: SCRYPT_KEYSTORE,
        envKeystorePassword: VECTOR_PASSPHRASE,
        promptPassphrase,
        warn: noopWarn,
      });
      expect(promptPassphrase).not.toHaveBeenCalled();
      expect(result.privateKey).toBe(VECTOR_PRIVATE_KEY);
    });

    it('takes precedence over OPERATOR_PRIVATE_KEY', async () => {
      const result = await resolveCredential({
        env: 'mainnet',
        keystorePath: PBKDF2_KEYSTORE,
        envPrivateKey: ANVIL_KEY,
        envKeystorePassword: VECTOR_PASSPHRASE,
        warn: noopWarn,
      });
      expect(result.source).toBe('keystore');
      expect(result.privateKey).toBe(VECTOR_PRIVATE_KEY);
    });
  });
});

// The audit recorded "the key is never logged, createClients never prints it, error messages do
// not echo it" as verified-clean. These tests exist so the new keystore path cannot regress it.
describe('no key or passphrase reaches stdout/stderr', () => {
  async function captureOutput(run: () => Promise<unknown>): Promise<string> {
    let captured = '';
    const sink = (chunk: unknown) => {
      captured += String(chunk);
      return true;
    };
    const stdout = vi.spyOn(process.stdout, 'write').mockImplementation(sink as never);
    const stderr = vi.spyOn(process.stderr, 'write').mockImplementation(sink as never);
    const log = vi.spyOn(console, 'log').mockImplementation(sink as never);
    const error = vi.spyOn(console, 'error').mockImplementation(sink as never);
    try {
      await run().catch((e: Error) => {
        captured += e.message;
      });
    } finally {
      stdout.mockRestore();
      stderr.mockRestore();
      log.mockRestore();
      error.mockRestore();
    }
    return captured;
  }

  it('keystore success path emits neither passphrase nor decrypted key', async () => {
    const output = await captureOutput(() =>
      resolveCredential({
        env: 'mainnet',
        keystorePath: PBKDF2_KEYSTORE,
        envKeystorePassword: VECTOR_PASSPHRASE,
      })
    );
    expect(output).not.toContain(VECTOR_PASSPHRASE);
    expect(output).not.toContain(VECTOR_PRIVATE_KEY);
    expect(output).not.toContain(VECTOR_PRIVATE_KEY.slice(2));
  });

  it('keystore failure path emits neither passphrase nor key', async () => {
    const output = await captureOutput(() =>
      resolveCredential({
        env: 'mainnet',
        keystorePath: PBKDF2_KEYSTORE,
        envKeystorePassword: 'the-wrong-passphrase',
      })
    );
    expect(output).not.toContain('the-wrong-passphrase');
    expect(output).not.toContain(VECTOR_PRIVATE_KEY.slice(2));
  });

  it('OPERATOR_PRIVATE_KEY warning path does not emit the key', async () => {
    const output = await captureOutput(() =>
      resolveCredential({ env: 'mainnet', envPrivateKey: ANVIL_KEY })
    );
    expect(output).toMatch(/Warning/);
    expect(output).not.toContain(ANVIL_KEY);
  });

  it('argv rejection on mainnet does not echo the supplied key', async () => {
    const output = await captureOutput(() =>
      resolveCredential({ env: 'mainnet', privateKeyArg: ANVIL_KEY })
    );
    expect(output).toMatch(/not permitted/i);
    expect(output).not.toContain(ANVIL_KEY);
  });
});

describe('keystore decryption (Web3 Secret Storage V3)', () => {
  // Validates against the canonical published spec vector, not just our own round trip.
  it('decrypts the pbkdf2 spec vector', async () => {
    await expect(loadKeystoreFile(PBKDF2_KEYSTORE, VECTOR_PASSPHRASE)).resolves.toBe(
      VECTOR_PRIVATE_KEY
    );
  });

  // Cross-implementation check: fixture written by ethers v6, decrypted by our code.
  it('decrypts an ethers-generated scrypt keystore (capitalised "Crypto")', async () => {
    await expect(loadKeystoreFile(SCRYPT_KEYSTORE, VECTOR_PASSPHRASE)).resolves.toBe(
      VECTOR_PRIVATE_KEY
    );
  });

  it('rejects a wrong passphrase via the MAC check', async () => {
    await expect(loadKeystoreFile(PBKDF2_KEYSTORE, 'wrong')).rejects.toThrow(
      KEYSTORE_DECRYPT_FAILED
    );
  });

  // A wrong-passphrase error must not disclose the passphrase, the ciphertext, or the MAC.
  it('wrong-passphrase error leaks nothing', async () => {
    const passphrase = 'hunter2-super-secret';
    const error = await loadKeystoreFile(PBKDF2_KEYSTORE, passphrase).catch((e: Error) => e);
    const message = (error as Error).message;
    expect(message).not.toContain(passphrase);
    expect(message).not.toContain('5318b4d5'); // ciphertext prefix
    expect(message).not.toContain('517ead92'); // mac prefix
    expect(message).not.toContain(VECTOR_PRIVATE_KEY.slice(2, 10));
  });

  it('rejects unsupported cipher / kdf / version', () => {
    expect(() => decryptKeystore({ version: 1, crypto: {} }, 'x')).toThrow(/version/i);
    expect(() => decryptKeystore({ version: 3, crypto: { cipher: 'aes-256-cbc' } }, 'x')).toThrow(
      /cipher/i
    );
    expect(() =>
      decryptKeystore(
        {
          version: 3,
          crypto: {
            cipher: 'aes-128-ctr',
            ciphertext: '00'.repeat(32),
            cipherparams: { iv: '00'.repeat(16) },
            mac: '00'.repeat(32),
            kdf: 'bogus',
            kdfparams: { dklen: 32, salt: '00' },
          },
        },
        'x'
      )
    ).toThrow(/kdf/i);
  });

  it('rejects a non-object and a missing crypto section', () => {
    expect(() => decryptKeystore(null, 'x')).toThrow(/JSON object/);
    expect(() => decryptKeystore({ version: 3 }, 'x')).toThrow(/crypto/);
  });

  it('reports unreadable and non-JSON files without leaking the passphrase', async () => {
    const passphrase = 'another-secret';
    const missing = await loadKeystoreFile('/nonexistent/keystore.json', passphrase).catch(
      (e: Error) => e
    );
    expect((error_message(missing) as string).includes(passphrase)).toBe(false);
    expect(error_message(missing)).toMatch(/Failed to read keystore file/);

    const notJson = await loadKeystoreFile(
      join(__dirname, 'fixtures', 'contracts.csv'),
      passphrase
    ).catch((e: Error) => e);
    expect(error_message(notJson)).toMatch(/not valid JSON/);
    expect((error_message(notJson) as string).includes(passphrase)).toBe(false);
  });
});

function error_message(e: unknown): string {
  return (e as Error).message;
}
